spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:hkblog
    username: sa
    password:
    driver-class-name: org.h2.Driver


